apps/api/urls.py
from django.urls import include, path

from .views import TokenObtainView, TokenRevokeView

app_name = 'auth-api'


urlpatterns = [
    # path('v1/', include(([
    #     path('token/', TokenObtainView.as_view(), name='token_obtain'),
    #     path('revoke/', TokenRevokeView.as_view(), name='token_revoke'),
    # ], 'v1')))
]

apps/auth/urls.py
from django.conf import settings
from django.contrib.auth import views
from django.urls import include, path


from auth.views import (
    LoginView, LogoutView, connect_service_begin, connect_service_complete,
    disconnect_service, pass_reset_confirm_view, pass_reset_view,
)

app_name = 'auth'

social_patterns = [
    path('connect/<str:backend>/', connect_service_begin, name='begin'),
    path('complete/<str:backend>/', connect_service_complete, name='complete'),
    path('disconnect/<str:backend>/', disconnect_service, name='disconnect'),
]

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(permanent=False), name='logout'),

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # FIXME: rename like in `registration` app
    path('password_reset/', pass_reset_view, name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', pass_reset_confirm_view, name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]



if settings.IS_SOCIAL_ACCOUNTS_ENABLED:
    urlpatterns += [
        path('social/', include((social_patterns, 'social')))
    ]

apps/learning/urls.py
from django.conf.urls import include
from django.urls import path, re_path

from courses.urls import RE_COURSE_URI
from learning.study.views import ProgramsView

from .views import (
    CourseEnrollView, CourseNewsNotificationUpdate, CourseStudentsView,
    CourseUnenrollView
)

urlpatterns = [
    path("courses/", include([
        re_path(RE_COURSE_URI, include([
            path("enroll/", CourseEnrollView.as_view(), name="course_enroll"),
            path("unenroll/", CourseUnenrollView.as_view(), name="course_leave"),
            path("students/", CourseStudentsView.as_view(), name="course_students"),
            path("news/notifications/", CourseNewsNotificationUpdate.as_view(), name="course_news_notifications_read"),
        ])),
    ])),


    path('teaching/', include('learning.teaching.urls')),

    path('learning/', include('learning.study.urls')),
    path('learning/programs/', ProgramsView.as_view(), name='programs'),
]

lms/urls.py
from django_ses.views import SESEventWebhookView

from django.apps import apps
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from core.views import MarkdownHowToHelpView, MarkdownRenderView
from courses.views import TeacherDetailView
from lms.views import CourseOfferingsView, IndexView

admin.autodiscover()


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('robots.txt', TemplateView.as_view(template_name="lms/robots.txt", content_type="text/plain"), name='robots_txt'),

    path('', include('auth.urls')),

    path('api/', include('api.urls')),
    path('api/', include('learning.api.urls')),

    path('tools/markdown/preview/', MarkdownRenderView.as_view(), name='render_markdown'),
    path('commenting-the-right-way/', MarkdownHowToHelpView.as_view(), name='commenting_the_right_way'),

    path('', include('learning.urls')),

    path('courses/', CourseOfferingsView.as_view(), name="course_list"),
    path('', include('courses.urls')),
    path("courses/", include('learning.invitation.urls')),
    path('teachers/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),
    path('', include('users.urls')),

    path('notifications/', include("notifications.urls")),
    path('', include("staff.urls")),
    path('ses/event-webhook/', SESEventWebhookView.as_view(), name='aws_ses_events_webhook'),

    path('', include('alumni.urls')),
]

if not settings.USE_CLOUD_STORAGE:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Placing this urls under `admin` namespace needs a lot of customization
if apps.is_installed('django_rq'):
    urlpatterns += [path('narnia/django-rq/', include('django_rq.urls'))]

urlpatterns += [path('narnia/', admin.site.urls)]


if settings.DEBUG:
    from django.conf.urls import handler400, handler403, handler404, handler500
    urlpatterns += [
        path('400/', handler400, kwargs={'exception': Exception("400")}),
        path('403/', handler403, kwargs={'exception': Exception("403")}),
        path('404/', handler404, kwargs={'exception': Exception("404")}),
        path('500/', handler500),
    ]
    if apps.is_installed('debug_toolbar'):
        import debug_toolbar
        urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    if apps.is_installed('rosetta'):
        urlpatterns += [path('rosetta/', include('rosetta.urls'))]

apps/templates/_modal.html
<div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <span class="modal-title"></span>
            </div>
            <div class="modal-body">
                <div class="loading"><i class="fa fa-refresh fa-spin"></i></div>
            </div>
        </div>
    </div>
</div>

apps/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Log in" %}{% endblock title %}
{% block body_attrs %} class="sign-in"{% endblock body_attrs %}

{% block stylesheets %}
<style>
  .grecaptcha-badge {
    z-index: 1;
  }
</style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="container-box panel panel-body panel-default">
                <form id="sign-in" method="POST">
                    {% block form_legend %}
                        {% if has_next %}
                            {% if user.is_authenticated %}
                                <p>You are not authorized to view this page.
                                    Please log in with an authorized account.</p>
                            {% else %}
                                <p>Log in to continue</p>
                            {% endif %}
                        {% endif %}
                    {% endblock form_legend %}
                    {% csrf_token %}

                    <label for="{{ form.username.id_for_label }}">
                        <input class="form-control" type="text" name="{{ form.username.name }}" required="" class="form-control" {% if form.username.value %}value="{{ form.username.value }}"{% endif %}
                               placeholder="{{ form.username.label }}" id="{{ form.username.id_for_label }}" tabindex="3">
                        <span class="error-message">{{ form.username.errors }}</span>
                    </label>
                    <label for="{{ form.password.id_for_label }}" class="password-block">
                        <input class="form-control" type="password" name="{{ form.password.name }}" required="" {% if form.username.value %}value="{{ form.password.value }}"{% endif %}
                               placeholder="{{ form.password.label }}" id="{{ form.password.id_for_label }}" tabindex="4"
                               autocomplete="off">
                        <a class="forgot" title="{% trans "Password Reset" %}" href="{% url 'auth:password_reset' %}" tabindex="5">{% trans "Forgot?" %}</a>
                        <span class="error-message">{{ form.password.errors }}{% for error in form.non_field_errors  %}{{ error }}<br>{% endfor %}</span>
                    </label>
                    {{ form.captcha }}
                    <span class="error-message">{{ form.captcha.errors }}</span>
                    <input type="submit" class="btn btn-primary sign-up-in" value="{% trans "Sign in" %}" tabindex="6">
                </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/templates/markdown_how_to.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load markdown from core_tags %}

{% block hightlight_styles %}
<link href="{% static "v1/css/vendor/highlight-styles/github.css" %}" rel="stylesheet">
{% endblock hightlight_styles %}

{% block body_attrs %} class="gray"{% endblock body_attrs %}

{% block content %}
    <div class="container" id="comment-the-right-way-page">
        <div class="row">
            <div class="col-xs-9">
                <ol class="breadcrumb gray">
                    <li class="">Text Formatting Guide</li>
                </ol>
                <p>In all parts of the website, we use Markdown for text formatting and LaTeX for formulas.<br>Here’s a quick example to show what they can do.</p>
<div class="nav-tabs-horizontal nav-tabs-inverse">
    <ul class="nav nav-tabs nav-tabs-solid" data-plugin="nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a data-toggle="tab" href="#code-1" aria-controls="applicant" role="tab" aria-expanded="true">What you type</a>
        </li>
        <li role="presentation" class="">
            <a data-toggle="tab" href="#result-1" aria-controls="result-1" role="tab" aria-expanded="false">What you get</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="code-1" role="tabpanel">
            <div class="ubertext">
            <pre><code class="language-markdown hljs"># Markdown Quick Reference

Markdown and $\LaTeX$ are supported in the input field.

**bold text**

*italicized text*

`monospaced text`


Use an empty line to separate paragraphs:

Paragraph one.
Further content of the first paragraph.

Paragraph two.

You can add lists:

  * First item
  * Second item
    Further content of the second item
  * Third item

Note the empty line before and after the list.

You can use different levels of headings like this:

## Heading 2

### Heading 3


To add a code snippet, use this format:

```
# Useful comment
foo = 42
for i in range(foo):
    print("I <3 Computer Science")
```

Remember to leave an empty line before the backticks.

The same, but using 4 spaces:

    # Useful comment
    foo = 42
    for i in range(foo):
        print("I <3 Computer Science")

Surround formulas with dollar signs $F_n$.
To put a formula on a separate line, use double dollar signs: $$F_n = F_{n-1} + F_{n-2}$$

# LaTeX Quick Reference

Subscripts and superscripts: $x_i, x^j, x_i^j, x_{i+1}$.

Some functions and symbols: $\pi, e, \sin{x}, \log(\mathbf{V} + \mathbf{E})$.

Fractions: $\frac{1}{2}, \binom{6}{4}$.

Sums: $\sum_{i=0}^n i^2$.

Product: $f$, $o$ and $o$: $foo$.

Variable `foo`: $\mathtt{foo}$.</code></pre></div>
        </div>
        <div class="tab-pane" id="result-1" role="tabpanel">
<div class="ubertext">
{% markdown 3600 "markdown_how_to_v1" %}
# Markdown Quick Reference

Markdown and $\LaTeX$ are supported in the input field.

**bold text**

*italicized text*

`monospaced text`


Use an empty line to separate paragraphs:

Paragraph one.
Продолжение первого параграфа.

Paragraph two.

You can add lists:

  * First item
  * Second item
    Further content of the second item
  * Third item

Note the empty line before and after the list.

You can use different levels of headings like this:

## Heading 2

### Heading 3


To add a code snippet, use this format:

```
# Useful comment
foo = 42
for i in range(foo):
    print("I <3 Computer Science")
```

Remember to leave an empty line before the backticks.

The same, but using 4 spaces:

    # Useful comment
    foo = 42
    for i in range(foo):
        print("I <3 Computer Science")

Surround formulas with dollar signs $F_n$.
To put a formula on a separate line, use double dollar signs: $$F_n = F_{n-1} + F_{n-2}$$

# LaTeX Quick Reference

Subscripts and superscripts: $x_i, x^j, x_i^j, x_{i+1}$.

Some functions and symbols: $\pi, e, \sin{x}, \log(\mathbf{V} + \mathbf{E})$.

Fractions: $\frac{1}{2}, \binom{6}{4}$.

Sums: $\sum_{i=0}^n i^2$.

Product: $f$, $o$ and $o$: $foo$.

Variable `foo`: $\mathtt{foo}$.
{% endmarkdown %}
</div>


        </div>
    </div>
</div>
            </div>
        </div>
    </div>
{% endblock content %}